export const blogList = [
    {
        id: 1,
        title: "7 css tools you should be using",
        category: "development",
        subCategory: ['frontend', 'ui/ux', 'design'],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Fuga officiis tempora doloremque consequuntur, vel saepe? Magnam veritatis doloribus quisquam, dolor eaque iusto tempore aliquidea dolorum est voluptatem facere enim molestiae voluptate quo ipsum nisi dignissimos beatae qui. Debitis, minus?",            
        authorName: "John Doe",
        authorAvatar: "/images/avatar.png",
        createdAt: "June 03, 2021",
        cover: '/images/css.jpg',
    },
    {
        id: 2,
        title: "Milan places that highlight the city",
        category: "travel",
        subCategory: ['vacation', 'holidays', 'sight seeing'],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Fuga officiis tempora doloremque consequuntur, vel saepe? Magnam veritatis doloribus quisquam, dolor eaque iusto tempore aliquidea dolorum est voluptatem facere enim molestiae voluptate quo ipsum nisi dignissimos beatae qui. Debitis, minus?",            
        authorName: "John Doe",
        authorAvatar: "/images/avatar.png",
        createdAt: "June 03, 2021",
        cover: '/images/milan.jpg',
    },
    {
        id: 3,
        title: "Adventure in you",
        category: "adventure",
        subCategory: ['adrenaline', 'fitness', 'lifestyle'],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Fuga officiis tempora doloremque consequuntur, vel saepe? Magnam veritatis doloribus quisquam, dolor eaque iusto tempore aliquidea dolorum est voluptatem facere enim molestiae voluptate quo ipsum nisi dignissimos beatae qui. Debitis, minus?",            
        authorName: "John Doe",
        authorAvatar: "/images/avatar.png",
        createdAt: "June 03, 2021",
        cover: '/images/adventure.jpg',
    },
    {
        id: 4,
        title: "7 css tools you should be using",
        category: "development",
        subCategory: ['frontend', 'ui/ux', 'design'],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Fuga officiis tempora doloremque consequuntur, vel saepe? Magnam veritatis doloribus quisquam, dolor eaque iusto tempore aliquidea dolorum est voluptatem facere enim molestiae voluptate quo ipsum nisi dignissimos beatae qui. Debitis, minus?",            
        authorName: "John Doe",
        authorAvatar: "/images/avatar.png",
        createdAt: "June 03, 2021",
        cover: '/images/css.jpg',
    },
    {
        id: 5,
        title: "Milan places that highlight the city",
        category: "travel",
        subCategory: ['vacation', 'holidays', 'sight seeing'],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Fuga officiis tempora doloremque consequuntur, vel saepe? Magnam veritatis doloribus quisquam, dolor eaque iusto tempore aliquidea dolorum est voluptatem facere enim molestiae voluptate quo ipsum nisi dignissimos beatae qui. Debitis, minus?",            
        authorName: "John Doe",
        authorAvatar: "/images/avatar.png",
        createdAt: "June 03, 2021",
        cover: '/images/milan.jpg',
    },
    {
        id: 6,
        title: "Adventure in you",
        category: "adventure",
        subCategory: ['adrenaline', 'fitness', 'lifestyle'],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Fuga officiis tempora doloremque consequuntur, vel saepe? Magnam veritatis doloribus quisquam, dolor eaque iusto tempore aliquidea dolorum est voluptatem facere enim molestiae voluptate quo ipsum nisi dignissimos beatae qui. Debitis, minus?",            
        authorName: "John Doe",
        authorAvatar: "/images/avatar.png",
        createdAt: "June 03, 2021",
        cover: '/images/adventure.jpg',
    },
    {
        id: 7,
        title: "7 css tools you should be using",
        category: "development",
        subCategory: ['frontend', 'ui/ux', 'design'],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Fuga officiis tempora doloremque consequuntur, vel saepe? Magnam veritatis doloribus quisquam, dolor eaque iusto tempore aliquidea dolorum est voluptatem facere enim molestiae voluptate quo ipsum nisi dignissimos beatae qui. Debitis, minus?",            
        authorName: "John Doe",
        authorAvatar: "/images/avatar.png",
        createdAt: "June 03, 2021",
        cover: '/images/css.jpg',
    },
    {
        id: 8,
        title: "Fun places to travel visit",
        category: "travel",
        subCategory: ['vacation', 'holidays', 'sight seeing'],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Fuga officiis tempora doloremque consequuntur, vel saepe? Magnam veritatis doloribus quisquam, dolor eaque iusto tempore aliquidea dolorum est voluptatem facere enim molestiae voluptate quo ipsum nisi dignissimos beatae qui. Debitis, minus?",            
        authorName: "John Doe",
        authorAvatar: "/images/avatar.png",
        createdAt: "June 03, 2021",
        cover: '/images/milan.jpg',
    },
    {
        id: 9,
        title: "Adventure in you",
        category: "adventure",
        subCategory: ['adrenaline', 'fitness', 'lifestyle'],
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Fuga officiis tempora doloremque consequuntur, vel saepe? Magnam veritatis doloribus quisquam, dolor eaque iusto tempore aliquidea dolorum est voluptatem facere enim molestiae voluptate quo ipsum nisi dignissimos beatae qui. Debitis, minus?",            
        authorName: "John Doe",
        authorAvatar: "/images/avatar.png",
        createdAt: "June 03, 2021",
        cover: '/images/adventure.jpg',
    },
]